language: go
go:
  - 1.6.3

sudo: required

services:
  - docker

branches:
  only:
    - master
    - /^test_/
    - /^test-/

install:
  - go test -i .

script:
  - go test -v . && go build . && ./travis_docker_push.sh
