language: go
go:
- 1.14.1
sudo: required
services:
- docker
branches:
  only:
  - master
  - /^test_/
  - /^test-/
install:
- go test -race -i .
script:
- go test -race . && GOOS=linux GOARCH=amd64 go build -ldflags "-X main.buildSHA=${TRAVIS_COMMIT}" . && ./travis_docker_push.sh
