language: go
go:
  - 1.6.2

sudo: required

services:
  - docker

branches:
  only:
    - master
    - /^test_/
    - /^test-/

install:
  - go test -i ./...

script:
  - go test -v ./... && ./travis_docker_push.sh