name: Build and Deploy to GKE

# Adapted from https://docs.github.com/en/actions/guides/deploying-to-google-kubernetes-engine

on:
  push:
    branches:
      - main
      - "force-deploy-*"

concurrency: production

env:
  GKE_CLUSTER: dg
  GKE_ZONE: us-central1-c
  DEPLOYMENT_NAME: lekube
  IMAGE: lekube

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production
    concurrency: production-deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v1.1.0
        with:
          workload_identity_provider: "projects/852340051888/locations/global/workloadIdentityPools/github-deploy/providers/github-deploy"
          service_account: "lekube-deploy@personal-sites-1295.iam.gserviceaccount.com"
          create_credentials_file: true

      - id: get-gke-credentials
        uses: google-github-actions/get-gke-credentials@v1.0.1
        with:
          cluster_name: dg
          location: us-central1-c

      - id: gcloud-config-docker
        run: gcloud auth configure-docker -q us-central1-docker.pkg.dev

      - id: docker-build
        run: docker build -t us-central1-docker.pkg.dev/personal-sites-1295/deploys/lekube:v1-${GITHUB_SHA} .

      - id: docker-push
        run: docker push us-central1-docker.pkg.dev/personal-sites-1295/deploys/lekube:v1-${GITHUB_SHA}

      - id: sha256-of-docker-image
        run: echo "IMAGE_WITH_SHA256=$(docker inspect --format='{{index .RepoDigests 0}}' us-central1-docker.pkg.dev/personal-sites-1295/deploys/lekube:v1-${GITHUB_SHA})" >> "$GITHUB_OUTPUT"

      - id: check-output
        run: echo "found as ${{steps.sha256-of-docker-image.outputs.IMAGE_WITH_SHA256}}"

      - id: update-deploy
        run: kubectl -n prod set image deployment/howsmyssl $IMAGE=${{ steps.sha256-of-docker-image.outputs.IMAGE_WITH_SHA256 }}

      - id: rollout-status
        run: kubectl -n prod rollout status -timeout=5m deployments/${{ env.DEPLOYMENT_NAME }}
