name: Build and Deploy to GKE

# Adapted from https://docs.github.com/en/actions/guides/deploying-to-google-kubernetes-engine

on:
  push:
    branches:
      - main
      - "force-deploy-*"

concurrency: production

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dg
  GKE_ZONE: us-central1-c
  DEPLOYMENT_NAME: lekube
  IMAGE: lekube

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: "1.17.0"
      - name: Test
        run: |-
          go test -race ./...

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker
      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@v0.7.0
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      # Build the Docker image
      - name: Build
        run: |-
          docker build \
            --tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            .

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |-
          docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"

      # Grab the image's SHA256 so we can use it instead of a tag (that can be
      # modified underneath us). This has to be done after the image has been
      # pushed. https://stackoverflow.com/questions/39811230/why-doesnt-my-newly-created-docker-have-a-digest
      - name: Capture Docker image's SHA256
        id: image
        run: |-
          FULLIMAGE=$(docker inspect --format='{{index .RepoDigests 0}}' gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA);
          echo "::set-output name=fullimage::${FULLIMAGE}"
      - name: Update GKE deployment
        run: |-
          kubectl -n prod set image deployment/$DEPLOYMENT_NAME $IMAGE="${{ steps.image.outputs.fullimage }}"
          kubectl -n prod rollout status deployment/$DEPLOYMENT_NAME
